export const salesProducts = [
  {
    imageSrc: '/gamepad.png',
    altText: 'Game Pad',
    discount: 40,
    productName: 'HAVIT HV-G92 Gamepad',
    salesPrice: 120,
    originalPrice: 160,
    rating: 5,
    reviewsCount: 88,
    category: 'Gaming',
  },
  {
    imageSrc: '/gaming-monitor.png',
    altText: 'Monitor',
    discount: 30,
    productName: 'IPS LCD Gaming Monitor',
    salesPrice: 370,
    originalPrice: 400,
    rating: 5,
    reviewsCount: 99,
    category: 'Computer',
  },
  {
    imageSrc: '/blue-sneakers.png',
    altText: 'UrbanAir',
    discount: 25,
    productName: 'UrbanAir Pro',
    salesPrice: 375,
    originalPrice: 400,
    rating: 4,
    reviewsCount: 50,
    category: 'Footwear',
  },
  {
    imageSrc: '/luxury-chair.png',
    altText: 'S-Series Comfort Chair',
    discount: 40,
    productName: 'S-Series Comfort Chair',
    salesPrice: 120,
    originalPrice: 160,
    rating: 5,
    reviewsCount: 88,
    category: 'Furniture',
  },
  {
    imageSrc: '/retro-speaker.png',
    altText: 'Retro electronic speaker',
    discount: 35,
    productName: 'EchoVibe Classic',
    salesPrice: 960,
    originalPrice: 1160,
    rating: 4.5,
    reviewsCount: 75,
    category: 'Electronics',
  },
  {
    imageSrc: '/green-purse.png',
    altText: 'green women handbag',
    discount: 35,
    productName: 'Grande Vogue',
    salesPrice: 960,
    originalPrice: 1160,
    rating: 4.5,
    reviewsCount: 75,
    category: 'Accessories',
  },
  {
    imageSrc: '/skate.png',
    altText: 'Roller Skate',
    discount: -30,
    productName: 'Roller Skate',
    salesPrice: 370,
    originalPrice: 400,
    rating: 5,
    reviewsCount: 99,
    category: 'Footwear',
  },
  {
    imageSrc: '/daffle-bag.png',
    altText: 'Daffle bag',
    discount: 30,
    productName: 'Daffle Bag',
    salesPrice: 120,
    originalPrice: 160,
    rating: 4.5,
    reviewsCount: 75,
    category: 'Accessories',
  },
];

export const bestProducts = [
  {
    imageSrc: '/north-coat.png',
    altText: 'north coat',
    productName: 'The North Coat',
    salesPrice: 260,
    originalPrice: 360,
    rating: 5,
    reviewsCount: 65,
    category: 'Clothing',
  },
  {
    imageSrc: '/pink-handbag.png',
    altText: 'pink handbag',
    productName: 'LuxeBelle Bag',
    salesPrice: 960,
    originalPrice: 1160,
    rating: 4.5,
    reviewsCount: 65,
    category: 'Accessories',
  },
  {
    imageSrc: '/brown-shoe.png',
    altText: 'brown shoe',
    productName: 'TrailEdge 360',
    salesPrice: 960,
    originalPrice: 1160,
    rating: 4.5,
    reviewsCount: 75,
    category: 'Footwear',
  },
  {
    imageSrc: '/bookshelf.png',
    altText: 'book shelf',
    productName: 'Small BookShelf',
    salesPrice: 360,
    originalPrice: 240,
    rating: 5,
    reviewsCount: 65,
    category: 'Furniture',
  },
  {
    imageSrc: '/baking-mixer.png',
    altText: 'baking mixer',
    productName: 'Pastries Mixer',
    salesPrice: 160,
    originalPrice: 170,
    rating: 4.5,
    reviewsCount: 65,
    category: 'Appliances',
  },
  {
    imageSrc: '/fashion-sneakers.png',
    altText: 'stride x sneakers',
    productName: 'StrideX Nova',
    salesPrice: 375,
    originalPrice: 400,
    rating: 4,
    reviewsCount: 50,
    category: 'Footwear',
  },
  {
    imageSrc: '/perfume.png',
    altText: 'perfume',
    productName: 'Gucci Scent Perfume',
    salesPrice: 100,
    originalPrice: 80,
    rating: 5,
    reviewsCount: 88,
    category: 'Beauty',
  },
  {
    imageSrc: '/lamp.png',
    altText: 'lamp',
    productName: 'Lamp',
    salesPrice: 160,
    originalPrice: 120,
    rating: 4.5,
    reviewsCount: 60,
    category: 'Furniture',
  },
];

export const products = [
  {
    imageSrc: '/puppy-food.png',
    altText: 'dog food',
    productName: 'Breed Dry Dog Food',
    price: 100,
    rating: 3,
    reviewsCount: 35,
    category: 'Pet Supplies',
  },
  {
    imageSrc: '/camera.png',
    altText: 'camera',
    productName: 'CANON EOS DSLR Camera',
    price: 360,
    rating: 4,
    reviewsCount: 95,
    category: 'Camera',
  },
  {
    imageSrc: '/ideapad-gaming.png',
    altText: 'gaming laptop',
    productName: 'SUS FHD Gaming Laptop',
    price: 700,
    rating: 5,
    reviewsCount: 325,
    category: 'Laptops',
  },
  {
    imageSrc: '/curology.png',
    altText: 'curology product',
    productName: 'Curology Product Set',
    price: 500,
    rating: 4,
    reviewsCount: 145,
    category: 'Beauty',
  },
  {
    imageSrc: '/electric-car.png',
    altText: 'kids electric car',
    label: 'New',
    productName: 'Kids Electric Car',
    price: 960,
    rating: 5,
    reviewsCount: 65,
    colors: ['bg-red-500', 'bg-gray-600'],
    category: 'Toys',
  },
  {
    imageSrc: '/soccer.png',
    altText: 'soccer cleat',
    productName: 'Jr.Zoom Soccer Cleats',
    price: 1160,
    rating: 5,
    reviewsCount: 35,
    colors: ['bg-yellow-300', 'bg-blue-600'],
    category: 'Footwear',
  },
  {
    imageSrc: '/gamepad2.png',
    altText: 'game pad',
    label: 'New',
    productName: 'GP11 Shooter USB Gamepad',
    price: 660,
    rating: 4.5,
    reviewsCount: 55,
    colors: ['bg-gray-600', 'bg-gray-900'],
    category: 'Gaming',
  },
  {
    imageSrc: '/satin-jacket.png',
    altText: 'satin jacket',
    productName: 'Quilted Satin Jacket',
    price: 660,
    rating: 4.5,
    reviewsCount: 60,
    colors: ['bg-green-600', 'bg-red-800'],
    category: 'Clothing',
  },
  {
    imageSrc: '/stereo-headphone.png',
    altText: 'headphone',
    label: 'New',
    productName: 'Classic Headphone',
    price: 370,
    rating: 5,
    reviewsCount: 99,
    category: 'Headphones',
  },
  {
    imageSrc: '/sneakers.png',
    altText: 'velco sneaker',
    productName: 'Velco Sneakers',
    price: 375,
    rating: 5,
    reviewsCount: 50,
    colors: ['bg-red-300', 'bg-blue-300'],
    category: 'Footwear',
  },
  {
    imageSrc: '/luxury-chair.png',
    altText: 'luxury chair',
    label: 'New',
    productName: "De'X Chair",
    price: 100,
    rating: 3,
    reviewsCount: 35,
    colors: ['bg-orange-700', 'bg-gray-600'],
    category: 'Furniture',
  },
  {
    imageSrc: '/straw-hat.png',
    altText: 'straw hat',
    productName: 'Straw Hat',
    price: 370,
    rating: 5,
    reviewsCount: 99,
    category: 'Accessories',
  },
];
