export const products = [
  {
    imageSrc: "/gamepad.png",
    altText: "Game Pad",
    discount: "-40%",
    productName: "HAVIT HV-G92 Gamepad",
    salesPrice: "$120",
    originalPrice: "$160",
    rating: 5,
    reviewsCount: 88,
  },
  {
    imageSrc: "/wired-keyboard.png",
    altText: "Keyboard",
    discount: "-35%",
    productName: "AK-900 Wired KeyBoard",
    salesPrice: "$960",
    originalPrice: "$1160",
    rating: 4.5,
    reviewsCount: 75,
  },
  {
    imageSrc: "/gaming-monitor.png",
    altText: "Monitor",
    discount: "-30%",
    productName: "IPS LCD Gaming Monitor",
    salesPrice: "$370",
    originalPrice: "$400",
    rating: 5,
    reviewsCount: 99,
  },
  {
    imageSrc: "/luxury-chair.png",
    altText: "Chair",
    discount: "-25%",
    productName: "IPS Luxury Chair",
    salesPrice: "$375",
    originalPrice: "$400",
    rating: 4,
    reviewsCount: 50,
  },
  {
    imageSrc: "/wired-keyboard.png",
    altText: "Keyboard",
    discount: "-35%",
    productName: "AK-900 Wired KeyBoard",
    salesPrice: "$960",
    originalPrice: "$1160",
    rating: 4.5,
    reviewsCount: 75,
  },
  {
    imageSrc: "/gamepad.png",
    altText: "Game Pad",
    discount: "-40%",
    productName: "HAVIT HV-G92 Gamepad",
    salesPrice: "$120",
    originalPrice: "$160",
    rating: 5,
    reviewsCount: 88,
  },
  {
    imageSrc: "/gaming-monitor.png",
    altText: "Monitor",
    discount: "-30%",
    productName: "IPS LCD Gaming Monitor",
    salesPrice: "$370",
    originalPrice: "$400",
    rating: 5,
    reviewsCount: 99,
  },
];
