export const products = [
  {
    id: 1,
    imageSrc: "/puppy-food.png",
    altText: "dog food",
    productName: "Breed Dry Dog Food",
    price: 100,
    rating: 3,
    reviewsCount: 35,
  },
  {
    id: 2,
    imageSrc: "/camera.png",
    altText: "camera",
    productName: "CANON EOS DSLR Camera",
    price: 360,
    rating: 4,
    reviewsCount: 95,
  },
  {
    id: 3,
    imageSrc: "/ideapad-gaming.png",
    altText: "gaming laptop",
    productName: "SUS FHD Gaming Laptop",
    price: 700,
    rating: 5,
    reviewsCount: 325,
  },
  {
    id: 4,
    imageSrc: "/curology.png",
    altText: "curology product",
    productName: "Curology Product Set",
    price: 500,
    rating: 4,
    reviewsCount: 145,
  },
  {
    id: 5,
    imageSrc: "/electric-car.png",
    altText: "kids electric car",
    label: "New",
    productName: "Kids Electric Car",
    price: 960,
    rating: 5,
    reviewsCount: 65,
    colors: [
      { id: "red", className: "bg-red-500" },
      { id: "gray", className: "bg-gray-600" },
    ],
  },
  {
    id: 6,
    imageSrc: "/soccer.png",
    altText: "soccer cleat",
    productName: "Jr.Zoom Soccer Cleats",
    price: 1160,
    rating: 5,
    reviewsCount: 35,
    colors: [
      { id: "yellow", className: "bg-yellow-300" },
      { id: "orange-red", className: "bg-orange-red" },
    ],
  },
  {
    id: 7,
    imageSrc: "/gamepad2.png",
    altText: "game pad",
    label: "New",
    productName: "GP11 Shooter USB Gamepad",
    price: 660,
    rating: 4.5,
    reviewsCount: 55,
    colors: [
      { id: "gray-600", className: "bg-gray-600" },
      { id: "gray-900", className: "bg-gray-900" },
    ],
  },
  {
    id: 8,
    imageSrc: "/satin-jacket.png",
    altText: "satin jacket",
    productName: "Quilted Satin Jacket",
    price: 660,
    rating: 4.5,
    reviewsCount: 60,
    colors: [
      { id: "green", className: "bg-green-800" },
      { id: "orange-red", className: "bg-orange-red" },
    ],
  },
  {
    id: 9,
    imageSrc: "/gaming-monitor.png",
    altText: "monitor",
    label: "New",
    productName: "IPS LCD Gaming Monitor",
    price: 370,
    rating: 5,
    reviewsCount: 99,
  },
  {
    id: 10,
    imageSrc: "/sneakers.png",
    altText: "Velco Sneaker",
    productName: "Velco Sneakers",
    price: 375,
    rating: 5,
    reviewsCount: 50,
    colors: [
      { id: "red", className: "bg-red-300" },
      { id: "blue", className: "bg-blue-300" },
    ],
  },
  {
    id: 11,
    imageSrc: "/luxury-chair.png",
    altText: "luxury chair",
    label: "New",
    productName: "De'X Chair",
    price: 100,
    rating: 3,
    reviewsCount: 35,
    colors: [
      { id: "orange", className: "bg-orange-700" },
      { id: "gray", className: "bg-gray-600" },
    ],
  },
  {
    id: 12,
    imageSrc: "/skate.png",
    altText: "Roller Skate",
    productName: "Roller Skate",
    price: 370,
    rating: 5,
    reviewsCount: 99,
  },
];
